### ISSUE TITLE
No module named 'colorlog'

### ISSUE THREAD

**Issue by AIRobotZhang** [openpsi-project/ReaLHF#41]
安装后报如下错误：
Successfully installed realhf-0.3.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/root/ReaLHF/realhf/__init__.py", line 4, in <module>
    from .api.core.config import ModelFamily
  File "/root/ReaLHF/realhf/api/core/config.py", line 5, in <module>
    import realhf.base.topology as topology
  File "/root/ReaLHF/realhf/base/topology.py", line 8, in <module>
    import realhf.base.logging as logging
  File "/root/ReaLHF/realhf/base/logging.py", line 5, in <module>
    import colorlog
ModuleNotFoundError: No module named 'colorlog'

**Comment by garrett4wade** [comment]
Please run `pip3 install -r requirements.txt` first, as illustrated in the [documentation](https://openpsi-project.github.io/ReaLHF/install.html). I will fix that in README. Thank you for your report!
