### ISSUE TITLE
Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by AIRobotZhang** [openpsi-project/ReaLHF#44]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/ReaLHF/realhf/apps/remote.py", line 242, in <module>
    main()
  File "/root/ReaLHF/realhf/apps/remote.py", line 238, in main
    args.func(args)
  File "/root/ReaLHF/realhf/apps/remote.py", line 92, in main_worker
    realhf.system.run_worker(
  File "/root/ReaLHF/realhf/system/__init__.py", line 58, in run_worker
    raise e
  File "/root/ReaLHF/realhf/system/__init__.py", line 54, in run_worker
    worker.run()
  File "/root/ReaLHF/realhf/system/worker_base.py", line 660, in run
    raise e
  File "/root/ReaLHF/realhf/system/worker_base.py", line 631, in run
    r = self._poll()
  File "/root/ReaLHF/realhf/system/model_worker.py", line 798, in _poll
    self.__lazy_setup()
  File "/root/ReaLHF/realhf/system/model_worker.py", line 318, in __lazy_setup
    model.module.instantiate()
  File "/root/ReaLHF/realhf/impl/model/nn/real_llm_api.py", line 219, in instantiate
    h()
  File "/root/ReaLHF/realhf/impl/model/nn/real_llm_api.py", line 893, in <lambda>
    lambda: getattr(m, f"from_{hf_model_family}")(
  File "/root/ReaLHF/realhf/impl/model/__init__.py", line 47, in _load_from_hf
    return r.load(model, load_dir, init_critic_from_actor)
  File "/root/ReaLHF/realhf/impl/model/conversion/hf_registry.py", line 156, in load
    raise RuntimeError(f"Error loading checkpoint from {path}: {e}")
RuntimeError: Error loading checkpoint from model-00002-of-00004.safetensors: Error while deserializing header: MetadataIncompleteBuffer

**Comment by garrett4wade** [comment]
It is probably because your downloaded checkpoint file is corrupted.

**Comment by AIRobotZhang** [comment]
> It is probably because your downloaded checkpoint file is corrupted.

Thank you!
