### ISSUE TITLE
How to debug remote subprocess?

### ISSUE THREAD

**Issue by metaqiang** [openpsi-project/ReaLHF#81]
I'm encountering an issue while attempting to execute the ReaLHF/examples/scripts/local/rw.sh script using the Docker image recommended in the documentation (docker.io/garrett4wade/real-gpu:24.03-py3-0.3.0). 

Despite following the provided instructions, the script fails to run on my Ubuntu 18.04 server with CUDA driver version 12.1 and NVIDIA Driver Version 530.30.02. 

We also run `python -c "import torch;print(torch.cuda.is_available())"` and `python -c "import torch;print(torch.cuda.device_count())"`, the result is True and 8. 

Can you tell me how to successfully run the script? thanks~

---

Errors:

20241105-21:15:06.793 worker ERROR: Worker encountered error ProcessGroupNCCL is only supported with GPUs, no GPUs found!
Traceback (most recent call last):
  File "/realhf/src/ReaLHF/realhf/system/worker_base.py", line 629, in run
    r = self._poll()
  File "/realhf/src/ReaLHF/realhf/system/model_worker.py", line 872, in _poll
    self.__lazy_setup()
  File "/realhf/src/ReaLHF/realhf/system/model_worker.py", line 209, in __lazy_setup
    self.__pg_info = global_comm.setup_global_comm(
  File "/realhf/src/ReaLHF/realhf/impl/model/comm/global_comm.py", line 129, in setup_global_comm
    torch.distributed.init_process_group(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 89, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1312, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1533, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(
ValueError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
20241105-21:15:06.795 Model Worker INFO: Model worker 1 exit with status ERROR.
20241105-21:15:06.795 system ERROR: Worker model_worker/1 failed with exception: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
20241105-21:15:06.795 system ERROR: Traceback (most recent call last):
  File "/realhf/src/ReaLHF/realhf/system/__init__.py", line 54, in run_worker
    worker.run()
  File "/realhf/src/ReaLHF/realhf/system/worker_base.py", line 658, in run
    raise e
  File "/realhf/src/ReaLHF/realhf/system/worker_base.py", line 629, in run
    r = self._poll()
  File "/realhf/src/ReaLHF/realhf/system/model_worker.py", line 872, in _poll
    self.__lazy_setup()
  File "/realhf/src/ReaLHF/realhf/system/model_worker.py", line 209, in __lazy_setup
    self.__pg_info = global_comm.setup_global_comm(
  File "/realhf/src/ReaLHF/realhf/impl/model/comm/global_comm.py", line 129, in setup_global_comm
    torch.distributed.init_process_group(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 89, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1312, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1533, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(
ValueError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!

**Comment by garrett4wade** [comment]
The first thing in my mind is the drvier version mismatch. [The base image requires NV driver version>=545.](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-24-03.html#rel-24-03). But this may not be the only issue. Have you set CUDA_VISIBLE_DEVICES in your environment? Can you try printing the CUDA_VISIBLE_DEVICES in each worker? According to [this script](https://github.com/openpsi-project/ReaLHF/blob/main/realhf/base/gpu_utils.py), it should be "i" for the i-th model worker.

**Comment by metaqiang** [comment]
Thank you, we have successfully run rw.sh by adding CUDA_VISIBLE_DEVICES, and adding --shm-size 16G to start the docker container.

**Comment by metaqiang** [comment]
有个调试的问题还想咨询下。

我们在ppo.sh中python3后新增了-m debugpy --listen xxxx，并在launch.json中新增了attach到此端口的调试命令。通过这种方式可以很方便地在vscode中调试quickstart.py。

但在启动remote时，使用的是subprocess.popen，我们想知道如何方便地单步调试remote子进程内的代码。

谢谢，期待您的回复！

**Comment by garrett4wade** [comment]
Frankly, I use print to debug. IMO it's impossible to inspect the worker process in the debug mode.

Writing unittests with mocks may be another feasible solution.

**Comment by metaqiang** [comment]
thanks~
